name: Artifact

on: [push]


env:
  ARTIFACT_NAME: myartifact
  
jobs:
 main:
 runs on: ubuntu-latest
 steps:
 - name:check out the code
   uses:actions/checkout@v1.2
 - name:actions/upload-artifactory@v1.2
   with:
   name:${{ env.ARTIFACT_NAME }}
   path: .
 
